### ISSUE TITLE
TestFlight beta

### ISSUE THREAD

**Issue by habi** [wtimme/OSM-Surveyor#2]
I'd love to test the app, but the TestFlight beta link does not work for me, the TestFlight app tells me that 'This beta isn't accepting any new testers right now'.
Is the beta already fully booked?

**Comment by wtimme** [comment]
Hey @habi and @dennisahlqvist,

Thanks for the feedback! I've just checked App Store Connect, and there does not seem to be a limit on testers for this particular testing group. I've then gone ahead and created a new Beta version that is now live for all testers. Could you please give the link in the README another go and let me know if it works for you?

Thanks in advance, and have a great day!

**Comment by habi** [comment]
Works fine for me now.
Thanks for looking into it!
