### ISSUE TITLE
Unable To Build - Missing Pods

### ISSUE THREAD

**Issue by pqhf5kd** [wtimme/OSM-Surveyor#3]
I'm not familiar with Pods, should they be included in the repository or should I install Cocoa Pods?

**Comment by wtimme** [comment]
Hey @pqhf5kd,

Thanks for bringing this up! Indeed, the README does not contain instructions on how to get started. With #4, I've added them. Could you give it a quick look and see if that works for you? I would then merge the pull request. Thanks in advance!

**Comment by pqhf5kd** [comment]
Built successfully, thanks :)
